theme: jekyll-theme-dinky
title: Prerna Shukla's Portfolio
description: Hi! I'm Prerna Shukla, a student at the Rutgers Honors College pursuing a double major in Computer Science and Psychology. I am a software enthusiast passionate about technology and innovation.
